version: 2.1
orbs:
  heroku: circleci/heroku@1.2.6
  node: circleci/node@4.3.0
jobs:
  install-node:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          install-yarn: true
      - run: node --version
  run-tests:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/express-prj/node_modules
          override-ci-command: npm install
      - run: npm run test
workflows:
  heroku_deploy:
    jobs:
      - heroku/deploy-via-git:
          requires:
            - install-node
            - run-tests
          app-name: $HEROKU_PRODUCTION_APP_NAME
          filters:
            branches:
              only: master
          pre-steps:
            - checkout
            - run: npm test

      - heroku/deploy-via-git:
          requires:
                - install-node
                - run-tests
          app-name: $HEROKU_STAGING_APP_NAME
          filters:
            branches:
              only: staging
          pre-steps:
            - checkout
            - run: npm test