version: 2.1
orbs:
  heroku: circleci/heroku@1.2.6
  node: circleci/node@4.3.0
jobs:
  run-tests:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/express-prj/node_modules
          override-ci-command: npm install
      - run: npm run test
workflows:
  heroku_deploy:
    jobs:
      - run-tests
      - heroku/deploy-via-git:
          requires:
            - install-node
          app-name: $HEROKU_PRODUCTION_APP_NAME
          filters:
            branches:
              only: master
          pre-steps:
            - checkout

      - heroku/deploy-via-git:
          requires:
                - install-node
          app-name: $HEROKU_STAGING_APP_NAME
          filters:
            branches:
              only: staging
          pre-steps:
            - checkout