version: 2.1
jobs:
  staging-deploy:
    executor: heroku/default
    app-name: $HEROKU_STAGING_APP_NAME
    filters:
      branches:
        only: staging
    steps:
      - checkout
      - heroku/install
      - run:
          name: Running tests
          command: yarn test
      - heroku/deploy-via-git
  production-deploy:
    executor: heroku/default
    app-name: $HEROKU_PRODUCTION_APP_NAME
    filters:
      branches:
        only: master
    steps:
      - checkout
      - heroku/install
      - run:
          name: Running tests
          command: yarn test
      - heroku/deploy-via-git
orbs:
  heroku: circleci/heroku@1.2.6
workflows:
  heroku_deploy:
    jobs:
      - deploy
