version: 2.1
orbs:
  heroku: circleci/heroku@1.2.6
  node: circleci/node@2.0.2
workflows:
  heroku_deploy:
    jobs:
      - heroku/deploy-via-git:
          app-name: $HEROKU_PRODUCTION_APP_NAME
          filters:
            branches:
              only: master
          pre-steps:
            - checkout
            - node/with-cache:
                steps:
                  - run: npm install
            - run: npm test

      - heroku/deploy-via-git:
          app-name: $HEROKU_STAGING_APP_NAME
          filters:
            branches:
              only: staging
          pre-steps:
            - checkout
            - node/with-cache:
                steps:
                  - run: npm install
            - run: npm test