version: 2.1
orbs:
  heroku: circleci/heroku@1.2.6
workflows:
  heroku_deploy:
    jobs:
      - staging:
          app-name: $HEROKU_PRODUCTION_APP_NAME
          branch: master
      - production:
          app-name: $HEROKU_STAGING_APP_NAME
          branch: staging